version: "3"
services:
  database:
    image: "postgres"
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: microshop
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"